In [3]:
import torch

A = torch.randn(2,4)
print(A.shape)
print(A)

B = A.view(2, 2, 2)
print(B.shape)
print(B)

torch.Size([2, 4])
tensor([[-0.6602, -0.2000, -0.7404,  0.4162],
        [-1.1267, -1.1360,  1.2097,  0.3960]])
torch.Size([2, 2, 2])
tensor([[[-0.6602, -0.2000],
         [-0.7404,  0.4162]],

        [[-1.1267, -1.1360],
         [ 1.2097,  0.3960]]])


In [4]:
C = A + A
print(C)

tensor([[-1.3204, -0.4000, -1.4807,  0.8324],
        [-2.2534, -2.2721,  2.4193,  0.7920]])


In [5]:
a = [1,2,3]
b = [4,5,6]
print(a + b)

[1, 2, 3, 4, 5, 6]
